globals:
  process: false
parser: babel-eslint
plugins:
  - import
  - react
rules:

  # POSSIBLE ERRORS

  comma-dangle:
    - 2
    - always
  no-cond-assign:
    - 2
    - always
  no-console:
    - 1
    -
      allow:
        - error
  no-constant-condition: 2
  no-control-regex: 2
  no-debugger: 2
  no-dupe-args: 2
  no-dupe-keys: 2
  no-duplicate-case: 2
  no-empty: 2
  no-empty-character-class: 2
  no-ex-assign: 2
  no-extra-boolean-cast: 2
  no-extra-parens: 2
  no-extra-semi: 2
  no-func-assign: 2
  no-inner-declarations: 2
  no-invalid-regexp: 2
  no-irregular-whitespace: 2
  no-negated-in-lhs: 2
  no-obj-calls: 2
  no-prototype-builtins: 2
  no-regex-spaces: 2
  no-sparse-arrays: 2
  no-unexpected-multiline: 2
  no-unreachable: 2
  no-unsafe-finally: 2
  use-isnan: 2
  valid-jsdoc: 2
  valid-typeof: 2

  # BEST PRACTISES

  # accessor-pairs: 0
  array-callback-return: 2
  block-scoped-var: 2
  complexity: 2
  # consistent-return: 0
  curly: 2
  # default-case: 0
  dot-location:
    - 2
    - property
  dot-notation: 2
  eqeqeq: 2
  guard-for-in: 2
  no-alert: 2
  no-caller: 2
  no-case-declarations: 2
  no-div-regex: 2
  no-else-return: 2
  no-empty-function: 2
  no-empty-pattern: 2
  no-eq-null: 2
  no-eval: 2
  no-extend-native: 2
  no-extra-bind: 2
  no-extra-label: 2
  no-fallthrough: 2
  no-floating-decimal: 2
  # no-implicit-coercion: 0
  # no-implicit-globals: 0
  no-implied-eval: 2
  no-invalid-this: 2
  no-iterator: 2
  no-labels: 2
  no-lone-blocks: 2
  no-loop-func: 2
  # no-magic-numbers: 0
  # no-multi-spaces: 0
  no-multi-str: 2
  no-native-reassign: 2
  no-new: 2
  no-new-func: 2
  no-new-wrappers: 2
  no-octal: 2
  no-octal-escape: 2
  no-param-reassign: 2
  no-proto: 2
  no-redeclare: 2
  no-return-assign:
    - 2
    - always
  no-script-url: 2
  no-self-assign: 2
  no-self-compare: 2
  no-sequences: 2
  no-throw-literal: 2
  no-unmodified-loop-condition: 2
  no-unused-expressions: 2
  no-unused-labels: 2
  no-useless-call: 2
  no-useless-concat: 2
  no-useless-escape: 2
  no-void: 2
  # no-warning-comments: 0
  no-with: 2
  radix:
    - 2
    - as-needed
  # vars-on-top: 0
  wrap-iife:
    - 2
    - inside
  yoda:
    - 2
    - never

  # VARIABLES

  init-declarations: 2
  no-catch-shadow: 2
  no-delete-var: 2
  no-label-var: 2
  no-shadow: 2
  no-shadow-restricted-names: 2
  no-undef: 2
  no-undef-init: 2
  # no-undefined: 0
  no-unused-vars: 2
  no-use-before-define: 2

  # STYLISTIC ISSUES

  array-bracket-spacing:
    - 2
    - always
  block-spacing: 2
  brace-style:
    - 2
    - stroustrup
  camelcase: 2
  comma-spacing: 2
  comma-style: 2
  computed-property-spacing:
    - 2
    - never
  consistent-this: 2
  # eol-last: 0
  func-names: 2
  func-style:
    - 2
    - declaration
  # id-blacklist: 0
  # id-length: 0
  # id-match: 0
  indent:
    - 2
    - 2
    -
      SwitchCase: 1
      VariableDeclarator:
        const: 3
        let: 2
        var: 2
  jsx-quotes: 2
  key-spacing:
    - 2
    -
      mode: minimum
  keyword-spacing: 0
  # linebreak-style: 0
  lines-around-comment:
    - 2
    -
      allowArrayEnd: true
      allowArrayStart: true
      allowBlockEnd: true
      allowBlockStart: true
      allowObjectEnd: true
      allowObjectStart: true
      beforeLineComment: true
  max-depth:
    - 2
    - 2
  # max-len: 0
  # max-lines: 0
  max-nested-callbacks:
    - 2
    -
      max: 2
  max-params:
    - 2
    -
      max: 5
  # max-statements: 0
  max-statements-per-line: 2
  new-cap: 2
  new-parens: 2
  newline-after-var: 2
  newline-before-return: 2
  newline-per-chained-call: 2
  no-array-constructor: 2
  no-bitwise: 2
  no-continue: 2
  # no-inline-comments: 0
  # no-lonely-if: 0
  # BUG: no-mixed-operators: 2
  no-mixed-spaces-and-tabs: 2
  no-multiple-empty-lines:
    - 2
    -
      max: 3
  # no-negated-condition: 0
  no-nested-ternary: 2
  no-new-object: 2
  # no-plusplus: 0
  # no-restricted-syntax: 0
  no-spaced-func: 2
  # no-ternary: 0
  no-trailing-spaces: 2
  # no-underscore-dangle: 0
  no-unneeded-ternary: 2
  no-whitespace-before-property: 2
  # object-curly-newline: 0
  object-curly-spacing:
    - 2
    - always
  object-property-newline: 2
  one-var:
    - 2
    - never
  one-var-declaration-per-line:
    - 2
    - always
  operator-assignment: 2
  operator-linebreak:
    - 2
    - before
    -
      overrides:
        "?": after
        ":": after
  padded-blocks:
    - 2
    - never
  quote-props:
    - 2
    - as-needed
  quotes:
    - 2
    - single
  # require-jsdoc: 0
  semi:
    - 2
    - never
  semi-spacing: 2
  sort-vars: 2
  space-before-blocks: 2
  space-before-function-paren:
    - 2
    - never
  space-in-parens: 2
  space-infix-ops: 2
  space-unary-ops: 2
  spaced-comment: 2
  # unicode-bom: 0
  wrap-regex: 2

  # ECMASCRIPT 6

  arrow-body-style:
    - 2
    - always
  arrow-parens: 2
  arrow-spacing: 2
  constructor-super: 2
  generator-star-spacing:
    - 2
    - after
  no-class-assign: 2
  no-confusing-arrow: 2
  no-const-assign: 2
  no-dupe-class-members: 2
  no-duplicate-imports: 2
  no-new-symbol: 2
  # no-restricted-imports: 0
  no-this-before-super: 2
  no-useless-computed-key: 2
  no-useless-constructor: 2
  # BUG: no-useless-rename: 2
  no-var: 2
  object-shorthand: 2
  prefer-arrow-callback: 2
  prefer-const: 2
  # prefer-reflect: 0
  prefer-rest-params: 2
  prefer-spread: 2
  prefer-template: 2
  require-yield: 2
  # BUG: rest-spread-spacing: 2
  # sort-imports: 0
  template-curly-spacing:
    - 2
    - always
  yield-star-spacing:
    - 2
    - before

  # IMPORT

  import/default: 2
  import/export: 2
  import/extensions: 2
  import/imports-first: 2
  import/named: 2
  import/namespace: 2
  import/newline-after-import: 2
  import/no-amd: 2
  import/no-commonjs: 2
  import/no-duplicates: 2
  import/no-mutable-exports: 2
  import/no-named-as-default-member: 2
  import/no-named-as-default: 2
  import/no-nodejs-modules: 2
  import/order:
    - 2
    -
      groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index

  # REACT

  react/no-danger: 2
  react/no-deprecated: 2
  react/no-did-mount-set-state: 2
  react/no-did-update-set-state: 2
  react/no-direct-mutation-state: 2
  react/no-is-mounted: 2
  react/no-multi-comp: 2
  react/no-string-refs: 2
  react/no-unknown-property: 2
  react/prefer-es6-class: 2
  react/prop-types: 2
  react/react-in-jsx-scope: 2
  react/self-closing-comp: 2
  react/sort-prop-types: 2
  react/wrap-multilines: 2

  # REACT JSX

  react/jsx-boolean-value:
    - 2
    - never
  react/jsx-closing-bracket-location: 2
  react/jsx-curly-spacing:
    - 2
    - always
  react/jsx-equals-spacing: 2
  react/jsx-indent-props:
    - 2
    - 2
  react/jsx-indent:
    - 2
    - 2
  react/jsx-key: 2
  react/jsx-max-props-per-line: 2
  react/jsx-no-duplicate-props: 2
  react/jsx-no-undef: 2
  react/jsx-pascal-case: 2
  react/jsx-sort-props:
    - 2
    -
      shorthandFirst: true
  react/jsx-space-before-closing: 2
  react/jsx-uses-react: 2
  react/jsx-uses-vars: 2